[package]
name = "rust-template"
version = "0.0.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.58"
description = ""
categories = []
keywords = []

[features]
default = ["std"]
std = []

[dependencies]


[dev-dependencies]

